# -*- coding: utf-8 -*-
"""Tower of Hanoi 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14yZI2fOQt2OQ9MR9Eny9F6OqGwu8uSRN
"""

line = int(input("Enter the count of lines : "))
step = int(input("Enter the step size : "))
value = 1

for i in range(line) :
    print("  " * (line - i - 1), end = "")
    for _ in range(i + 1) :
        print(value, end = "   ")
    print()
    value += step
value = 1
print("\n")
for line_num in range(1, line + 1) :
    print(f"Line {(line_num + 1)} : {value}s : {value} * {line_num} ")
    value += step